services:
  ecommerce-db:
    image: postgres:16-alpine
    container_name: ecommerce-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ecommerce-redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data:/data

  ecommerce-api:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: ecommerce-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "5001:5000"
    depends_on:
      ecommerce-db:
        condition: service_healthy
      ecommerce-redis:
        condition: service_started
